import { MarketSignal } from './types';

// Market News Data - Auto-generated by Market News agent
// Generated: 2026-03-08T15:00:00+01:00
// Consolidated canonical source for Market Intel (seeded to database on build)

export const marketNewsData: MarketSignal[] = [
  // Competitor Funding & Launches
  {
    id: "figma-ai-series-d-2026",
    type: "funding",
    date: "2026-03-06",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/03/06/figma-ai-1b-series-d/",
    title: "Figma Raises $1B at $15B Valuation for AI-Powered Design Tools",
    context: "Figma announced a $1B Series D led by a16z and Sequoia, doubling down on AI features. New 'Figma AI' can generate design systems from text prompts and auto-prototype user flows. Competitor impact: High for design-to-code tools.",
    competitor: "Figma",
    relevance: 5,
    tags: ["funding", "ai", "design-tools", "series-d"]
  },
  {
    id: "notion-workflow-launch-2026",
    type: "launch",
    date: "2026-03-05",
    source: "Notion Blog",
    url: "https://www.notion.so/blog/workflows-launch",
    title: "Notion Launches 'Workflows' to Automate Cross-Tool Processes",
    context: "Notion Workflow Builder allows no-code automation connecting Notion with 50+ tools including Slack, Jira, and GitHub. Features AI-powered workflow suggestions based on workspace usage patterns. Free tier includes 100 workflow runs/month.",
    competitor: "Notion",
    relevance: 4,
    tags: ["launch", "automation", "workflows", "integration"]
  },
  {
    id: "linear-insights-beta-2026",
    type: "launch",
    date: "2026-03-04",
    source: "Linear Blog",
    url: "https://linear.app/blog/insights-beta",
    title: "Linear Insights Enters Beta: AI-Powered Project Analytics",
    context: "Linear launched Insights beta, providing AI-generated project health scores, bottleneck predictions, and team velocity forecasts. Integrates with GitHub/GitLab for code-level metrics. Competes directly with mission control dashboards.",
    competitor: "Linear",
    relevance: 5,
    tags: ["launch", "beta", "analytics", "ai", "project-management"]
  },
  {
    id: "raycast-pro-ai-2026",
    type: "pricing",
    date: "2026-03-03",
    source: "Raycast",
    url: "https://www.raycast.com/pro-ai",
    title: "Raycast Pro AI: $10/Month for Unlimited AI Commands",
    context: "Raycast introduced Pro AI tier with unlimited GPT-4.5 and Claude 3.7 Sonnet commands. Features custom AI workflows, team shared commands, and local model support (Ollama). Free tier reduced to 50 AI commands/month.",
    competitor: "Raycast",
    relevance: 3,
    tags: ["pricing", "ai", "launcher", "productivity"]
  },
  {
    id: "github-copilot-workspace-ga",
    type: "launch",
    date: "2026-03-02",
    source: "GitHub Blog",
    url: "https://github.blog/2026-03-02-copilot-workspace-ga/",
    title: "GitHub Copilot Workspace Goes Generally Available",
    context: "Copilot Workspace, the AI-powered development environment, is now GA. Features include natural language issue-to-PR workflows, automated testing suggestions, and one-click deployment to Azure/GCP/AWS. $39/month per user for teams.",
    competitor: "GitHub",
    relevance: 5,
    tags: ["launch", "ga", "ai-coding", "ide", "copilot"]
  },
  {
    id: "vercel-ship-2026",
    type: "event",
    date: "2026-03-01",
    source: "Vercel",
    url: "https://vercel.com/ship",
    title: "Vercel Ship 2026: AI SDK 5.0, v0 Enterprise, Edge Functions 2.0",
    context: "Vercel's annual conference announced AI SDK 5.0 with multi-provider agent support, v0 Enterprise with SOC2 compliance and SSO, and Edge Functions 2.0 with 5-minute execution limits. New 'Deploy Button' marketplace for one-click app deployment.",
    competitor: "Vercel",
    relevance: 4,
    tags: ["event", "ai-sdk", "v0", "edge-functions", "conference"]
  },
  {
    id: "anthropic-claude-enterprise",
    type: "launch",
    date: "2026-02-28",
    source: "Anthropic",
    url: "https://www.anthropic.com/news/claude-enterprise",
    title: "Claude for Enterprise Launches with SSO, Audit Logs, 500K Context",
    context: "Anthropic launched Claude for Enterprise with native SSO (Okta, Azure AD), comprehensive audit logs, and 500K token context window. $50/user/month. Includes Claude Code integration for repository-wide analysis and refactoring.",
    competitor: "Anthropic",
    relevance: 4,
    tags: ["launch", "enterprise", "sso", "audit", "claude-code"]
  },
  {
    id: "slack-ai-agent-sdk-2026",
    type: "launch",
    date: "2026-02-27",
    source: "Slack API",
    url: "https://api.slack.com/ai-agent-sdk",
    title: "Slack Releases AI Agent SDK for Building Native Agents",
    context: "Slack's new AI Agent SDK enables developers to build agents that operate natively within Slack. Features include message intent detection, thread-aware context, and built-in action handlers. Salesforce Agentforce integration included.",
    competitor: "Slack",
    relevance: 4,
    tags: ["launch", "sdk", "ai-agents", "integration", "salesforce"]
  },
  {
    id: "supabase-edge-functions-deno-2",
    type: "launch",
    date: "2026-02-26",
    source: "Supabase",
    url: "https://supabase.com/blog/edge-functions-deno-2",
    title: "Supabase Edge Functions Upgrades to Deno 2.0",
    context: "Supabase Edge Functions now runs on Deno 2.0, bringing 40% faster cold starts, native npm package support, and improved TypeScript performance. New regional deployment options in 15 additional regions.",
    competitor: "Supabase",
    relevance: 3,
    tags: ["launch", "deno-2", "edge-functions", "performance"]
  },
  {
    id: "stripe-agent-toolkit-2026",
    type: "launch",
    date: "2026-02-25",
    source: "Stripe",
    url: "https://stripe.com/blog/agent-toolkit",
    title: "Stripe Agent Toolkit: Build AI Agents That Accept Payments",
    context: "Stripe released Agent Toolkit, a set of APIs and SDKs for building AI agents that can process payments, manage subscriptions, and handle refunds autonomously. Includes built-in fraud detection and compliance checks.",
    competitor: "Stripe",
    relevance: 4,
    tags: ["launch", "payments", "ai-agents", "fintech", "api"]
  },
  {
    id: "asana-intelligence-suite-2026",
    type: "launch",
    date: "2026-02-24",
    source: "Asana",
    url: "https://asana.com/guide/help/preview/intelligence-suite",
    title: "Asana Intelligence Suite: AI Project Manager with Smart Goals",
    context: "Asana launched Intelligence Suite featuring AI-generated project timelines, smart goal recommendations based on historical data, and automated status updates. Targets mid-market project managers with $25/user/month pricing.",
    competitor: "Asana",
    relevance: 3,
    tags: ["launch", "ai", "project-management", "automation"]
  },
  {
    id: "openai-operator-api-beta",
    type: "launch",
    date: "2026-02-23",
    source: "OpenAI",
    url: "https://openai.com/blog/operator-api-beta",
    title: "OpenAI Operator API Enters Beta: AI Agents That Browse the Web",
    context: "OpenAI's Operator API allows developers to build agents that can browse websites, fill forms, and make purchases on behalf of users. Includes built-in safety guardrails and user confirmation flows. $200/month for 1,000 operations.",
    competitor: "OpenAI",
    relevance: 5,
    tags: ["launch", "beta", "operator", "web-browsing", "agents"]
  }
];

export default marketNewsData;
