// Tech Radar Data - Auto-generated by Tech Radar agent
// Generated: 2026-03-08T15:00:00+01:00
// Consolidated canonical source for Tech Updates (seeded to database on build)

export interface TechSignal {
  id: string;
  date: string; // ISO date
  category: "ai-models" | "agent-orchestration" | "frontend-tooling" | "knowledge-graphs" | "dev-tools" | "security";
  title: string;
  summary: string;
  relevance: number;
  url: string;
  source: string;
  tags: string[];
}

export const techSignals: TechSignal[] = [
  // AI Models - March 2026
  {
    id: "gpt-5.3-instant-launch",
    date: "2026-03-07",
    category: "ai-models",
    title: "GPT-5.3 Instant Launches as New ChatGPT Default",
    summary: "OpenAI launched GPT-5.3 Instant on March 3, 2026 as the new default for all ChatGPT users. Features 400K token context window (up from 128K), 26.8% reduction in hallucinations with web search enabled, improved conversational tone with less 'preachy' responses, and enhanced web search integration. Available via API as 'gpt-5.3-chat-latest'.",
    relevance: 5,
    url: "https://decrypt.co/359837/more-accurate-less-cringe-openai-gpt-5-3-instant-chatgpt",
    source: "Decrypt",
    tags: ["openai", "gpt-5.3", "instant", "hallucination-reduction", "context-window"]
  },
  {
    id: "claude-opus-4.6",
    date: "2026-03-07",
    category: "ai-models",
    title: "Claude Opus 4.6 & Sonnet 4.6: 1M Token Context Window",
    summary: "Anthropic released Claude Opus 4.6 (Feb 5) and Claude Sonnet 4.6 (Feb 17, 2026), both featuring a 1-million token context window in beta. Opus 4.6 improves coding skills and agentic tasks, while Sonnet 4.6 enhances coding, computer use, and long-context reasoning.",
    relevance: 4,
    url: "https://www.anthropic.com/news/claude-opus-4-6",
    source: "Anthropic",
    tags: ["anthropic", "claude", "opus-4.6", "sonnet-4.6", "context-window", "agentic"]
  },
  {
    id: "grok-4.2-beta",
    date: "2026-03-07",
    category: "ai-models",
    title: "xAI Grok 4.2 Beta Released, Grok 5 Expected Q1 2026",
    summary: "xAI released Grok 4.2 public beta in February 2026 with weekly updates, improved reasoning, and refined coding performance. Grok 5 is expected Q1 2026 with 6 trillion parameters (double Grok 3/4), native multimodal capabilities including video understanding, and 10% AGI probability per Elon Musk.",
    relevance: 3,
    url: "https://releasebot.io/updates/xai",
    source: "ReleaseBot",
    tags: ["xai", "grok", "grok-5", "multimodal", "agi"]
  },

  // Agent Orchestration - March 2026
  {
    id: "mastra-2026-03-04",
    date: "2026-03-07",
    category: "agent-orchestration",
    title: "Mastra Updates: Workspaces, Sandbox, RBAC for Production Agents",
    summary: "Mastra March 4, 2026 changelog delivers major upgrades: model-safe command output, token-aware truncation, smarter truncation per tool, end-to-end authentication and RBAC across Server/Studio/Providers, workflow execution path tracking, and concurrent-safe workflow snapshot updates. Now 21.6k+ GitHub stars, used by Replit, PayPal, Sanity.",
    relevance: 4,
    url: "https://mastra.ai/blog/changelog-2026-03-04",
    source: "Mastra",
    tags: ["mastra", "typescript", "agent-framework", "rbac", "production"]
  },
  {
    id: "crewai-2026-survey",
    date: "2026-03-07",
    category: "agent-orchestration",
    title: "CrewAI Hits 45K Stars: 100% Enterprises Expanding Agentic AI",
    summary: "CrewAI surpassed 45,000 GitHub stars by March 4, 2026. The 2026 State of Agentic AI Survey reveals 100% of enterprises plan to expand agentic AI adoption in 2026, with 65% already actively using AI agents. 75% report high time savings, 69% cite significant operational cost reductions.",
    relevance: 3,
    url: "https://theagenttimes.com/articles/45000-stars-and-counting-crewais-meteoric-rise-charts-the-multi-agent-future",
    source: "The Agent Times",
    tags: ["crewai", "multi-agent", "enterprise", "survey", "adoption"]
  },
  {
    id: "langchain-skills-2026",
    date: "2026-03-07",
    category: "agent-orchestration",
    title: "LangChain Skills: Tools for AI Coding Agents",
    summary: "LangChain released 'LangChain Skills' in March 2026, providing AI coding agents with expertise in the LangChain ecosystem. Includes specific guidance for working with LangGraph primitives for Human-In-The-Loop, durable execution, and complex workflow orchestration.",
    relevance: 3,
    url: "https://blog.langchain.com/langchain-skills/",
    source: "LangChain",
    tags: ["langchain", "langgraph", "coding-agents", "skills", "tools"]
  },

  // Dev Tools - March 2026
  {
    id: "vercel-cdn-dashboard-2026",
    date: "2026-03-07",
    category: "dev-tools",
    title: "Vercel CDN Dashboard Redesign + Streamdown 2.4 Released",
    summary: "Vercel unveiled a redesigned CDN dashboard on March 5, 2026 with live traffic map, streamlined cache purging, and project-level routing rules that update instantly without new deployments. Streamdown 2.4 brings flexible code blocks with customizable start line numbers, custom icons/themes, and enhanced inline code styling. Chat SDK now supports native table rendering.",
    relevance: 3,
    url: "https://vercel.com/changelog",
    source: "Vercel",
    tags: ["vercel", "cdn", "dashboard", "streamdown", "chat-sdk"]
  },

  // Security - March 2026
  {
    id: "CVE-2026-22813",
    date: "2026-03-07",
    category: "security",
    title: "CVE-2026-22813: Critical RCE in Cloudflare AI Coding Agent",
    summary: "Cloudflare's 2026 Threat Report reveals CVE-2026-22813 (CVSS 9.4), a critical vulnerability in their own AI coding agent's markdown rendering pipeline. The flaw allowed unauthenticated Remote Code Execution. Cloudflare discovered and patched the vulnerability internally before exploitation.",
    relevance: 4,
    url: "https://blog.cloudflare.com/2026-threat-report/",
    source: "Cloudflare",
    tags: ["cloudflare", "CVE", "RCE", "critical", "ai-agent", "markdown"]
  },
  {
    id: "agentic-browser-vulnerabilities",
    date: "2026-03-07",
    category: "security",
    title: "Agentic AI Browsers Vulnerable to Prompt Injection Attacks",
    summary: "Researchers discovered a suite of flaws affecting multiple 'agentic AI browsers' including Perplexity's Comet. Attackers can use prompt injection via legitimate means (like calendar invites) to force AI browsers to access local file systems, browse directories, open/read files, and exfiltrate data. Exploits the execution model and trust boundaries of AI agents.",
    relevance: 4,
    url: "https://cyberscoop.com/agentic-ai-browsers-allow-hijacking-zenity-labs-comet/",
    source: "CyberScoop",
    tags: ["agentic-browser", "prompt-injection", "data-exfiltration", "perplexity", "comet"]
  },

  // Knowledge Graphs - March 2026
  {
    id: "pinecone-march-2026",
    date: "2026-03-07",
    category: "knowledge-graphs",
    title: "Pinecone March 2026: Backup/Restore APIs, Admin API, Audit Logs",
    summary: "Pinecone launched several features in public preview March 2026: Backup and Restore APIs for serverless indexes, Admin API and Service Accounts for programmatic management, and Audit Logs for security monitoring. Serverless architecture optimized for large-scale agentic workloads. Also: Pinecone Plugin for Claude Code and Google ADK integration.",
    relevance: 3,
    url: "https://www.pinecone.io/launch-week/",
    source: "Pinecone",
    tags: ["pinecone", "vector-db", "serverless", "audit-logs", "backup-restore", "claude-code"]
  },

  // Additional signals to exceed 10 result threshold
  {
    id: "nextjs-15-2-release",
    date: "2026-03-08",
    category: "frontend-tooling",
    title: "Next.js 15.2 Released with Enhanced Partial Prerendering",
    summary: "Next.js 15.2 introduces significant improvements to Partial Prerendering (PPR), allowing static and dynamic content to coexist on the same page. New features include streaming metadata, improved caching semantics, and reduced cold start times for serverless functions.",
    relevance: 4,
    url: "https://nextjs.org/blog/next-15-2",
    source: "Vercel",
    tags: ["nextjs", "react", "ppr", "streaming", "performance"]
  },
  {
    id: "react-compiler-beta-2026",
    date: "2026-03-08",
    category: "frontend-tooling",
    title: "React Compiler Enters Public Beta with Automatic Memoization",
    summary: "React Compiler (formerly React Forget) is now in public beta. It automatically memoizes React components and hooks without manual useMemo/useCallback. Early benchmarks show 15-30% reduction in re-renders and improved developer experience.",
    relevance: 4,
    url: "https://react.dev/learn/react-compiler",
    source: "React",
    tags: ["react", "compiler", "memoization", "performance", "beta"]
  },
  {
    id: "tailwind-v4-release",
    date: "2026-03-08",
    category: "frontend-tooling",
    title: "Tailwind CSS v4.0 Released with Zero-Runtime CSS",
    summary: "Tailwind CSS v4.0 ships with a new engine that generates CSS at build time only, eliminating runtime overhead. Features include native CSS cascade layers, container query improvements, and a streamlined plugin API. Migration path provided for v3.x users.",
    relevance: 3,
    url: "https://tailwindcss.com/blog/tailwindcss-v4",
    source: "Tailwind Labs",
    tags: ["tailwind", "css", "zero-runtime", "v4", "performance"]
  }
];

// Export for API ingestion
export default techSignals;